services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    vasyaxy\Swoole\Component\AtomicCounter:
        factory: ['vasyaxy\Swoole\Component\AtomicCounter', fromZero]

    vasyaxy\Swoole\Component\ExceptionArrayTransformer:

    vasyaxy\Swoole\Server\RequestHandler\ExceptionHandler\ProductionExceptionHandler:

    vasyaxy\Swoole\Server\RequestHandler\ExceptionHandler\JsonExceptionHandler:

    vasyaxy\Swoole\Server\RequestHandler\ExceptionRequestHandler:
        arguments:
            $decorated: '@vasyaxy\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler'

    vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\SetRequestRuntimeConfiguration:

    vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInjectorInterface: '@vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInjector'

    vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInjector:
        arguments:
            $responseProcessor: '@response_processor.headers_and_cookies.streamed'

    vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\RequestFactoryInterface:
        class: vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\RequestFactory

    vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface:
        class: vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessor

    vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\NoOpStreamedResponseProcessor:
        decorates: vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface
        decoration_priority: -100
        arguments:
            - '@vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\NoOpStreamedResponseProcessor.inner'

    response_processor.headers_and_cookies.default:
        class: vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\ResponseHeadersAndStatusProcessor
        decorates: vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface
        arguments:
            - '@response_processor.headers_and_cookies.default.inner'

    vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\StreamedResponseProcessor:

    response_processor.headers_and_cookies.streamed:
        class: vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\ResponseHeadersAndStatusProcessor
        decorates: vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\StreamedResponseProcessor
        arguments:
            - '@response_processor.headers_and_cookies.streamed.inner'

    vasyaxy\Swoole\Server\RequestHandler\RequestHandlerInterface:
        alias: vasyaxy\Swoole\Server\RequestHandler\ExceptionRequestHandler

    vasyaxy\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler:

    vasyaxy\Swoole\Server\RequestHandler\LimitedRequestHandler:

    vasyaxy\Swoole\Server\LifecycleHandler\SigIntHandler:

    vasyaxy\Swoole\Server\Runtime\CallableBootManagerFactory:

    vasyaxy\Swoole\Server\Session\SwooleTableStorage:
        factory: ['vasyaxy\Swoole\Server\Session\SwooleTableStorage', 'fromDefaults']

    vasyaxy\Swoole\Server\Session\StorageInterface:
        alias: vasyaxy\Swoole\Server\Session\SwooleTableStorage

    vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorage:

    vasyaxy\Swoole\Server\Runtime\BootableInterface:
        class: vasyaxy\Swoole\Server\Runtime\CallableBootManager
        factory: ['@vasyaxy\Swoole\Server\Runtime\CallableBootManagerFactory', make]
        arguments: [!tagged 'swoole_bundle.bootable_service']
        autoconfigure: false

    vasyaxy\Swoole\Server\HttpServer:

    vasyaxy\Swoole\Server\WorkerHandler\WorkerStartHandlerInterface:
        class: vasyaxy\Swoole\Server\WorkerHandler\NoOpWorkerStartHandler

    vasyaxy\Swoole\Server\LifecycleHandler\ServerStartHandlerInterface:
        class: vasyaxy\Swoole\Server\LifecycleHandler\NoOpServerStartHandler

    vasyaxy\Swoole\Server\LifecycleHandler\ServerShutdownHandlerInterface:
        class: vasyaxy\Swoole\Server\LifecycleHandler\NoOpServerShutdownHandler

    vasyaxy\Swoole\Server\LifecycleHandler\ServerManagerStartHandlerInterface:
        class: vasyaxy\Swoole\Server\LifecycleHandler\NoOpServerManagerStartHandler

    vasyaxy\Swoole\Server\LifecycleHandler\ServerManagerStopHandlerInterface:
        class: vasyaxy\Swoole\Server\LifecycleHandler\NoOpServerManagerStopHandler

    vasyaxy\Swoole\Server\TaskHandler\TaskHandlerInterface:
        class: vasyaxy\Swoole\Server\TaskHandler\NoOpTaskHandler

    vasyaxy\Swoole\Server\TaskHandler\TaskFinishedHandlerInterface:
        class: vasyaxy\Swoole\Server\TaskHandler\NoOpTaskFinishedHandler

    vasyaxy\Swoole\Server\Api\ApiServerClientFactory:

    vasyaxy\Swoole\Server\Api\ApiServerClient:
        factory: vasyaxy\Swoole\Server\Api\ApiServerClientFactory:newClient

    vasyaxy\Swoole\Server\Api\ApiServerInterface:
        class: vasyaxy\Swoole\Server\Api\ApiServer

    #  Could be helpful for projects that uses/have included proxy-manager
    #        lazy: true
    #        tags:
    #            - { name: proxy, interface: vasyaxy\Swoole\Server\Api\ApiServerInterface }

    vasyaxy\Swoole\Server\Config\Sockets:

    vasyaxy\Swoole\Server\HttpServerConfiguration:

    vasyaxy\Swoole\Server\Configurator\WithHttpServerConfiguration:

    vasyaxy\Swoole\Server\Configurator\WithServerShutdownHandler:

    vasyaxy\Swoole\Server\Configurator\WithServerStartHandler:

    vasyaxy\Swoole\Server\Configurator\WithServerManagerStartHandler:

    vasyaxy\Swoole\Server\Configurator\WithServerManagerStopHandler:

    vasyaxy\Swoole\Server\Configurator\WithWorkerStartHandler:

    vasyaxy\Swoole\Server\Configurator\WithTaskHandler:

    vasyaxy\Swoole\Server\Configurator\WithTaskFinishedHandler:

    vasyaxy\Swoole\Server\Configurator\CallableChainConfiguratorFactory:

    vasyaxy\Swoole\Server\Api\WithApiServerConfiguration:
        arguments:
            $requestHandler: '@swoole_bundle.server.api_server.request_handler'

    vasyaxy\Swoole\Server\Api\ApiServerRequestHandler:

    swoole_bundle.server.api_server.request_handler:
        class: vasyaxy\Swoole\Server\RequestHandler\ExceptionRequestHandler
        arguments:
            $decorated: '@vasyaxy\Swoole\Server\Api\ApiServerRequestHandler'

    swoole_bundle.server.http_server.configurator_collection:
        class: vasyaxy\Swoole\Component\GeneratedCollection
        arguments: [!tagged 'swoole_bundle.server_configurator']

    vasyaxy\Swoole\Server\Configurator\ConfiguratorInterface:
        alias: swoole_bundle.server.http_server.configurator

    swoole_bundle.session.table_storage:
        alias: vasyaxy\Swoole\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorage

    swoole_bundle.server.http_server.configurator.with_request_handler:
        class: vasyaxy\Swoole\Server\Configurator\WithRequestHandler
        autoconfigure: false

    swoole_bundle.server.http_server.configurator.with_limited_request_handler:
        class: vasyaxy\Swoole\Server\Configurator\WithRequestHandler
        autoconfigure: false
        arguments:
            $requestHandler: '@vasyaxy\Swoole\Server\RequestHandler\LimitedRequestHandler'

    swoole_bundle.server.http_server.configurator.with_sigint_handler:
        class: vasyaxy\Swoole\Server\Configurator\WithServerStartHandler
        autoconfigure: false
        arguments:
            $handler: '@vasyaxy\Swoole\Server\LifecycleHandler\SigIntHandler'
